### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by michaelficarra** [ranjitjhala/linter-hdevtools#2]
AtomLinter v0.x API has been deprecated. Please refer to the Linter docs to update to the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API

**Comment by ranjitjhala** [comment]
Whoops! Thanks for the heads up! Will look into this ASAP!

On Sat, Jul 11, 2015 at 8:46 PM, Michael Ficarra notifications@github.com
wrote:

> AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs
> to update and the latest API:
> https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ranjitjhala/linter-hdevtools/issues/2.

## 

Ranjit.

**Comment by ranjitjhala** [comment]
Fixed in 8f98d6ca642f27ad182fbdd71b767e6ae0e2ce02
should be good to go for the new atom 1.0 onwards...
