### ISSUE TITLE
Cannot find module in the test directory?

### ISSUE THREAD

**Issue by notcome** [ranjitjhala/linter-hdevtools#6]
I am using stack. There is a test-suite in my cabal file like this:

```
test-suite indescript-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Spec.hs
  build-depends:       base
                     , indescript
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010
```

I currently have a `test/Test/PopCorn.hs` and hdevtools is able to type check the file. However, I could not import this file in `test/Spec.hs`, even though `stack test` successfully compiles everything. Am I doing anything wrong? How to solve the issue?

Thank you!
(Writing unit test for the parser…I guess I couldn't work on the type checker until next week.)

**Comment by notcome** [comment]
Oh, the latest version of hdevtools solves the issue.

**Comment by ranjitjhala** [comment]
great, thanks!

On Saturday, October 31, 2015, Minsheng Liu notifications@github.com
wrote:

> Oh, the latest version of hdevtools solves the issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ranjitjhala/linter-hdevtools/issues/6#issuecomment-152774949
> .

## 

Ranjit.
